ui/src/components/ScalableBaseChart/scalable-base-chart.component.js
* added bugfix preventing the default scroll behaviour of the page when zooming in on a ScalableBaseChartComponent
=> bugfix for page scrolling

ui/src/components/SearchBox/index.js
* added functioning terminating condition to avoid endless loop in componentDidUpdate in SearchBox
=> #69: Bug with selecting a second Issue in Code Ownership River

ui/src/visualizations/dashboard/reducers/config.js
* fixing bug after PR/71 where local storage is broken
=> #78: Broken Local Storage

ui/src/components/ProgressBar/ProgressBar.js, ui/src/components/ProgressBar/index.js, ui/src/index.js
* blending out progress indicator in offline mode
=> #86: Fix Commit highlighting in Code Ownership River

lib/core/db/db.js, lib/models/Connection.js, lib/models/Model.js, package-lock.json, package.json
* migrating from arangojs 7 to arangojs 8
=> #90: ArangoJS 8 migration

ui/src/visualizations/VisualizationComponents/changes/chart/chart.js
* fixing changes chart so that all committers get displayed
=> #106: Merged Authors buggy in Changes Chart

lib/indexers/its/GitHubIndexer.js, lib/projectStructureHelper.js
* fixing paths in project structure helper
* fixing url in GitHubIndexer.js
=> #108: Execution not working after install on mac

ui/src/styles/styles.scss, ui/src/visualizations/dashboard/help.js, ui/src/visualizations/dashboard/styles.scss, ui/src/visualizations/dashboard/styles/help.scss, ui/src/visualizations/legacy/code-hotspots/css/help.scss, ui/src/visualizations/legacy/code-hotspots/help.js, ui/src/visualizations/legacy/code-hotspots/styles.scss, ui/src/visualizations/legacy/code-ownership-river/help.js, ui/src/visualizations/legacy/code-ownership-river/styles.scss, ui/src/visualizations/legacy/dashboard/help.js, ui/src/visualizations/legacy/dashboard/styles.scss, ui/src/visualizations/legacy/hotspot-dials/help.js, ui/src/visualizations/legacy/hotspot-dials/styles.scss, ui/src/visualizations/legacy/issue-impact/help.js, ui/src/visualizations/legacy/issue-impact/styles.scss, ui/src/visualizations/legacy/language-module-river/help.js, ui/src/visualizations/legacy/language-module-river/styles.scss
* adding help to dashboard
* refining help style across all visualizations and make it centralized editable
=> #110: Add Help to Dashboard

lib/models/Issue.js
- fixed issue where app crashes when issues and stakeholders are being connected
- #140
=> Feature/140: fix merge issues

ui/src/components/Sidebar/Sidebar.js, ui/src/components/UniversalSettings/universalSettings.js, ui/src/reducers/index.js, ui/src/visualizations/code-expertise/chart/chart.js, ui/src/visualizations/code-expertise/chart/details/index.js, ui/src/visualizations/code-expertise/chart/index.js, ui/src/visualizations/code-expertise/config/index.js, ui/src/visualizations/code-expertise/index.js, ui/src/visualizations/code-expertise/reducers/config.js, ui/src/visualizations/code-ownership/index.js
- various improvements for the code expertise visualization
- updated universal settings to react hooks
- visualizations now can hide irrelevant fields of the universal settings
- closes #142
=> Feature/142: Code Expertise Improvements

ui/src/components/Filepicker/ModuleLine.js, ui/src/components/Filepicker/index.js, ui/src/components/Filepicker/styles.scss, ui/src/components/Filepicker/utils.js, ui/src/database/database.js, ui/src/database/localDB.js, ui/src/database/localDB/commits.js, ui/src/database/serverDB.js, ui/src/database/serverDB/commits.js, ui/src/visualizations/code-expertise/chart/details/index.js, ui/src/visualizations/code-expertise/chart/index.js, ui/src/visualizations/code-expertise/config/index.js, ui/src/visualizations/code-expertise/reducers/data.js, ui/src/visualizations/code-expertise/sagas/helper.js, ui/src/visualizations/code-expertise/sagas/index.js, ui/src/visualizations/code-ownership/config/index.js, ui/src/visualizations/code-ownership/sagas/helper.js, ui/src/visualizations/code-ownership/sagas/index.js
- filepicker component now indicates ownership of modules/files
- closes #144
=> Feature/144: File Ownership Overview

ui/src/database/utils.js, ui/src/visualizations/code-expertise/chart/index.js
=> Feature/153: GitLab Bugfixes

.github/workflows/build-offline.yml
This reverts commit d07afb3f02d20a6c55c6d828e79eb094ffef2f7d.
=> Revert "#181: Updated trigger"

lib/core/provider/git.js, lib/indexers/vcs/GitIndexer.js, lib/models/Branch.js, lib/models/BranchFileConnection.js, lib/models/BranchFileFileConnection.js, test/backend/vcsIndexer.test.js
When a branch that is already persisted is deleted, remove the branch and all its connections (branch-files, branch-files-files) from the database
=> Feature/206 remove non-existent branches from database

binocular-frontend/vite.config.ts, docker/Dockerfile.frontend
- rolling back Dockerfile.frontend
- switching from react-swc to react in vite.config.ts
=> #212 Dockerfile installation bug

binocular-backend/binocular.ts, binocular-backend/cli/cli.ts, binocular-backend/utils/context.ts
- adding the option to cli to disable vcs indexing
=> #228 Disable VCS Indexer in CLI

binocular-backend/utils/projectStructureHelper.ts, binocular-frontend/package-lock.json, binocular-frontend/package.json, binocular-frontend/src/database/localDB.js, binocular-frontend/src/main.tsx, binocular-frontend/vite.config.ts, utils/json-utils.ts
=> Feature/245 Offline Launch Performance

binocular-frontend/src/database/localDB/commits.js, binocular-frontend/src/database/localDB/utils.js, binocular-frontend/src/database/serverDB/commits.js, binocular-frontend/src/database/utils.js, binocular-frontend/src/visualizations/VisualizationComponents/changes/sagas/index.ts, binocular-frontend/src/visualizations/code-expertise/sagas/helper.js, binocular-frontend/src/visualizations/code-ownership/sagas/helper.js, binocular-frontend/src/visualizations/code-ownership/sagas/index.js, foxx/types/commit.js
=> Feature/249 Commit History

binocular-backend/models/Model.ts, binocular-backend/test/ciIndexer.test.js, binocular-backend/test/db.test.js, binocular-backend/test/helper/db/testConnToModelConnection.ts, binocular-backend/test/helper/db/testConnection.ts, binocular-backend/test/helper/db/testModel.js, binocular-backend/test/helper/db/testModel.ts, binocular-backend/test/helper/git/gitTestData.js, binocular-backend/test/helper/github/gitHubTestData.js, binocular-backend/test/helper/gitlab/gitLabMock.js, binocular-backend/test/helper/gitlab/gitLabTestData.js, binocular-backend/test/helper/utils.js, binocular-backend/test/itsIndexer.test.js, binocular-backend/test/vcsIndexer.test.js, package.json
=> Feature/251 Additional Tests

.github/workflows/build-offline.yml
- update actions/deploy-pages dependency for deploy part in build-offline.yml
=> #281 Build Pipeline for Offline Build is broken

binocular-frontend/src/reducers/universalSettings.ts
- disable loading of the author list from the local storage
=> #309 Temporary fix author list
